export const contactStyles = {
  root: {
    py: { xs: 6, md: 10 },
    px: { xs: 2, sm: 4 },
    maxWidth: 680,
    mx: 'auto',
  },
  eyebrow: {
    fontSize: '0.8rem',
    fontWeight: 600,
    letterSpacing: '0.12em',
    textTransform: 'uppercase' as const,
    color: '#6366f1',
    mb: 1.5,
  },
  headline: {
    fontSize: { xs: '2rem', md: '2.75rem' },
    fontWeight: 800,
    lineHeight: 1.15,
    letterSpacing: '-0.03em',
    color: '#0f172a',
    mb: 2,
  },
  intro: {
    fontSize: '1.1rem',
    color: '#475569',
    lineHeight: 1.8,
    mb: 5,
  },
  form: {
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 3,
  },
  fieldLabel: {
    fontSize: '0.875rem',
    fontWeight: 600,
    color: '#1e293b',
    mb: 0.75,
  },
  submitButton: {
    alignSelf: 'flex-start',
    px: 4,
    py: 1.25,
    fontSize: '0.95rem',
    fontWeight: 600,
    backgroundColor: '#6366f1',
    textTransform: 'none' as const,
    borderRadius: 2,
    boxShadow: 'none',
    '&:hover': {
      backgroundColor: '#4f46e5',
      boxShadow: 'none',
    },
  },
}
